# Generated by Django 3.2 on 2021-04-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_finaldiscount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaldiscount',
            name='order',
        ),
    ]
